language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XUaKdoAPUpaRfWxNrXWec3inkKR2kmdVnJFo/ywOpOF/XOPujHEKxRRbAl3KyOsSElknOs7qy8OqoAXqdB0fKKhohfGu7uXriJm0pRLdIM1nzHjKMcntb6ieV4393smkMW8zDquJgMVxUVj/shRio3Yd0lpmPhJTyUcjRK8X5cAtv73A9HJkXRXOnL44GteukzY83ivanNjrx320XL5q97YY6ePXcquv33O8FVQ6tJax+OuFGNt/6m1Ygxl5/J8r7PqFIL+I54W9USZmXbfsXeubdIDFfYV72nUP4ZrsEBG4Gwl29aB4lS5D1tifEHtGJ+2ZpzM3zSGI5rTdA2S6RwTHDj9PD/afVhWN+ldXF5VmBXZiGRRWlieL9tvSuAQspi9IDoFSjb/ejZcpu2+HwKI6gcTu6oOT9/AMEd8ZZrfBxCZOVAk2ZqpayzqWlyKb335BH8y+tcYSmyECOQwc3JPqXJxeGTnALjQRaNM5ajnFj5pNx2WV8kjfAuRKwZbWKI1rd0YG8QPYSxsbeZUppq4yYyVXJ1kIKO7mL3Uil8zewgWmHyMsYbXwL/5WNA2GE66q8PbxjahS3zYn6aIhXVkUe/Je79j90uim1sq08BiCr7ArXAxmmg+SPVA7k2pRjnsDJBvgnQNLFmZKfqL3zxJQajFawNz4H4loajlcLMg=
  file:
    - 'rehype-autolink-headings.js'
    - 'rehype-autolink-headings.min.js'
  on:
    tags: true
